### ISSUE TITLE
Have you considered this?

### ISSUE THREAD

**Issue by EntropyHaos** [hhsnopek/ama#7]
Question = Have you considered arranging your commits so that you create a picture with this:

![screenshot 1](https://cloud.githubusercontent.com/assets/7077428/8748539/cfa2006a-2c60-11e5-93bb-4ea3fe071db6.jpg)

I see a guy on the right playing soccer, might be the artist thing though.
BTW - Congrats on hitting 500 / year!

**Comment by hhsnopek** [comment]
I have in the past, but I wanna keep my commit history as is. This way I can look back at my history and see my progress :) 

Thanks :D
