### ISSUE TITLE
Are you interested in stock markets?

### ISSUE THREAD

**Issue by aarroyoc** [hhsnopek/ama#8]

**Comment by hhsnopek** [comment]
I used to be into the stock market until the 2008 market scare, after that I started to program a lot more and haven't looked back. What about yourself @AdrianArroyoCalle ?

**Comment by aarroyoc** [comment]
Just starting! I've learnt with an online simulator [LaBolsaVirtual](http://labolsavirtual.com) and played with friends on the challenges. It's very funny see your friends investments and the ranking. And since the first of October I'm investing with real money. Currently, only European companies (EUR/USD conversions change too often).
